### ISSUE TITLE
Setting 是不是可以考虑加个是否加密字段

### ISSUE THREAD

**Issue by XiangZou2** [vipwan/Biwen.Settings#10]
Setting 是不是可以考虑加个是否加密字段

**Comment by vipwan** [comment]
你的意思是 编辑的时候加密字段不展示明文吗(如果存在的话)  还是说在仓储中加密 ?

**Comment by XiangZou2** [comment]
仓储中，加密存在数据库里

**Comment by vipwan** [comment]
嗯，很合理的需求，有时间我整上去 ，如果你愿意 可以pull 一起完善

**Comment by vipwan** [comment]
//加密提供者,PlainEncryptionProvider为默认实现
    options.UseEncryption<PlainEncryptionProvider>();

    options.UseSettingManagerOfEFCore(options =>
    {
        options.DbContextType = typeof(MyDbContext);
        options.EncryptionOption = new SettingOptions.EncryptionOptions
        {
            Enable = true //仓储是否开启加密
        };
    });

//目前这里实现上比较侵入. 在Manager内部加密解密; 如果新增Manager也需要自行处理,后续考虑抽象化
@XiangZou2
