### ISSUE TITLE
FluentValidation 版本问题

### ISSUE THREAD

**Issue by ioer2008** [vipwan/Biwen.Settings#15]
你好,我因为一些原因使用的FluentValidation v9.3,暂时无法升级到v11,这样是不是就没有办法使用Biwen.Settings了

**Comment by vipwan** [comment]
你好,针对你提到的版本,确实有些久远, 当前没有考虑支持历史版本,测试最低的兼容版本是**FluentValidation 11.1.0**,另外Biwen.Settings只支持`NET8+` ,缺失了几个源码涉及的函数如下: 
![image](https://github.com/vipwan/Biwen.Settings/assets/13956765/b5f592f6-8e79-4fa2-a41f-1fc51a7fe8c0)
